{{- if and .Values.nexora.auth.keys (not .Values.nexora.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexora-kit.fullname" . }}-auth
  labels:
    {{- include "nexora-kit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.nexora.auth.keys }}
  {{ .userId }}-key: {{ .key | b64enc | quote }}
  {{- end }}
{{- end }}
